# app.yaml (Google App Engine)
runtime: python39

env_variables:
  DATABASE_URL: "postgresql://user:password@/scam_detector?host=/cloudsql/project:region:instance"
  CLOUD_SQL_CONNECTION_NAME: "project:region:instance"

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: auto
  secure: always